export const ListLink = [
  { id: 1, to: "/phim-bo", title: "Phim bộ" },
  { id: 2, to: "/phim-le", title: "Phim lẻ" },
  { id: 3, to: "/tv-shows", title: "TV Shows" },
  { id: 4, to: "/hoat-hinh", title: "Hoạt hình" },
  { id: 5, to: "/dang-nhap", title: "Đăng nhập" },
];

export const categoryProps = {
  title: "Thể loại",
  genres: [
    "Hành Động",
    "Miền Tây",
    "Trẻ Em",
    "Lịch Sử",
    "Cổ Trang",
    "Chiến Tranh",
    "Viễn Tưởng",
    "Kinh Dị",
    "Tài Liệu",
    "Bí Ẩn",
    "Phim 18+",
    "Tình Cảm",
    "Tâm Lý",
    "Thể Thao",
    "Phiêu Lưu",
    "Âm Nhạc",
    "Gia Đình",
    "Học Đường",
    "Hài Hước",
    "Hình Sự",
    "Võ Thuật",
    "Khoa Học",
    "Thần Thoại",
    "Chính Kịch",
    "Kinh Điển",
  ],
  slug: [
    "hanh-dong",
    "mien-tay",
    "tre-em",
    "lich-su",
    "co-trang",
    "chien-tranh",
    "vien-tuong",
    "kinh-di",
    "tai-lieu",
    "bi-an",
    "phim-18",
    "tinh-cam",
    "tam-ly",
    "the-thao",
    "phieu-luu",
    "am-nhac",
    "gia-dinh",
    "hoc-duong",
    "hai-huoc",
    "hinh-su",
    "vo-thuat",
    "khoa-hoc",
    "than-thoai",
    "chinh-kich",
    "kinh-dien",
  ],
};

export const countryProps = {
  title: "Quốc gia",
  genres: [
    "Việt Nam",
    "Trung Quốc",
    "Thái Lan",
    "Hồng Kông",
    "Pháp",
    "Đức",
    "Hà Lan",
    "Mexico",
    "Thụy Điển",
    "Philippines",
    "Đan Mạch",
    "Thụy Sĩ",
    "Ukraina",
    "Hàn Quốc",
    "Âu Mỹ",
    "Ấn Độ",
    "Canada",
    "Tây Ban Nha",
    "Indonesia",
    "Ba Lan",
    "Malaysia",
    "Bồ Đào Nha",
    "UAE",
    "Châu Phi",
    "Ả Rập Xê Út",
    "Nhật Bản",
    "Đài Loan",
    "Anh",
    "Quốc Gia Khác",
    "Thổ Nhĩ Kỳ",
    "Nga",
    "Úc",
    "Brazil",
    "Ý",
    "Na Uy",
    "Nam Phi",
  ],
  slug: [
    // DÒNG NÀY RẤT QUAN TRỌNG: ĐẢM BẢO CÁC SLUG ĐỀU LÀ KHÔNG DẤU
    "viet-nam",
    "trung-quoc",
    "thai-lan",
    "hong-kong",
    "phap",
    "duc", // <-- ĐẢM BẢO LÀ "duc" chứ không phải "đuc"
    "ha-lan",
    "mexico",
    "thuy-dien",
    "philippines",
    "dan-mach",
    "thuy-si",
    "ukraina",
    "han-quoc",
    "au-my",
    "an-do",
    "canada",
    "tay-ban-nha",
    "indonesia",
    "ba-lan",
    "malaysia",
    "bo-dao-nha",
    "uae",
    "chau-phi",
    "a-rap-xe-ut",
    "nhat-ban",
    "dai-loan", // <-- ĐẢM BẢO LÀ "dai-loan" chứ không phải "đai-loan"
    "anh",
    "quoc-gia-khac",
    "tho-nhi-ky",
    "nga",
    "uc",
    "brazil",
    "y",
    "na-uy",
    "nam-phi",
  ],
};
