export const ListLink = [
  { id: 1, to: "/TongHop/phim-bo", title: "Phim bộ" },
  { id: 2, to: "/TongHop/phim-le", title: "Phim lẻ" },
  { id: 3, to: "/TongHop/tv-shows", title: "TV Shows" },
  { id: 4, to: "/TongHop/hoat-hinh", title: "Hoạt hình" },
  { id: 5, to: "/TongHop/hoat-hinh", title: "Đăng nhập" },
];
export const categoryProps = {
  title: "Thể loại",
  genres: [
    "Hành Động",
    "Miền Tây",
    "Trẻ Em",
    "Lịch Sử",
    "Cổ Trang",
    "Chiến Tranh",
    "Viễn Tưởng",
    "Kinh Dị",
    "Tài Liệu",
    "Bí Ẩn",
    "Phim 18+",
    "Tình Cảm",
    "Tâm Lý",
    "Thể Thao",
    "Phiêu Lưu",
    "Âm Nhạc",
    "Gia Đình",
    "Học Đường",
    "Hài Hước",
    "Hình Sự",
    "Võ Thuật",
    "Khoa Học",
    "Thần Thoại",
    "Chính Kịch",
    "Kinh Điển",
  ],
  slug: [
    "hanh-dong",
    "mien-tay",
    "tre-em",
    "lich-su",
    "co-trang",
    "chien-tranh",
    "vien-tuong",
    "kinh-di",
    "tai-lieu",
    "bi-an",
    "phim-18",
    "tinh-cam",
    "tam-ly",
    "the-thao",
    "phieu-luu",
    "am-nhac",
    "gia-dinh",
    "hoc-duong",
    "hai-huoc",
    "hinh-su",
    "vo-thuat",
    "khoa-hoc",
    "than-thoai",
    "chinh-kich",
    "kinh-dien",
  ],
};

export const countryProps = {
  title: "Quốc gia",
  genres: ["Trung Quốc", "Hàn Quốc", "Âu Mỹ", "Nhật Bản", "Việt Nam"],
};
